---
galaxy_info:
  role_name: security-hardening
  author: Sentience Robotics
  description: Security hardening including SSH configuration and access control
  company: Sentience Robotics
  license: GPL-3.0-only
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
  galaxy_tags:
    - security
    - ssh
    - access-control
    - hardening

dependencies: [] 