---
galaxy_info:
  role_name: user-environment
  author: Charles Madjeri
  description: User shell environment and development tools setup
  company: Sentience Robotics
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
  galaxy_tags:
    - shell
    - zsh
    - development
    - environment

dependencies:
  - role: system-foundation 