---
galaxy_info:
  role_name: network-configuration
  author: Charles Madjeri
  description: Network configuration including hostname, Wi-Fi, and networking setup
  company: Sentience Robotics
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
  galaxy_tags:
    - network
    - wifi
    - hostname
    - connectivity

dependencies: [] 